export const ADD_NEW_POST = '[POSTS] Add new post'
export const GET_ALL_POSTS = '[POSTS] Get all posts'
export const UPDATE_POST = '[POSTS] Update post'
export const LIKE_POST = '[POSTS] Like post'
export const SET_ACTIVE_POST = '[POSTS] Set active post'
export const DELETE_POST = '[DELETE] Delete post'
