export const ADD_NEW_POST = '[POSTS] Add new post'
export const GET_ALL_POSTS = '[POSTS] Get all posts'
export const GET_RECOMMENDED_POSTS = '[POSTS] Get recommended posts'
export const GET_POSTS_BY_SEARCH = '[POSTS] Get posts by search'
export const UPDATE_POST = '[POSTS] Update post'
export const LIKE_POST = '[POSTS] Like post'
export const COMMENT_POST = '[POSTS] Comment post'
export const SET_ACTIVE_POST = '[POSTS] Set active post'
export const DELETE_POST = '[DELETE] Delete post'

export const SIGN_UP = '[POST] Sign up'
export const SIGN_IN = '[POST] Sign in'
export const CHECK_IF_SIGNED_IN = '[POST] Check if signed in'
export const LOGOUT = '[POST] Logout'

export const START_LOADING = 'START_LOADING'
export const FINISH_LOADING = 'FINISH_LOADING'

export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'
